# -*- mode: ruby -*-
# vi: ft=ruby :

# provioning script for install ansible management deps.
# ansible needs python and aptitude, these are not installed by default.
$script = <<eof
sudo apt-get update
sudo apt-get --yes install python aptitude
eof

# vagrant settings
Vagrant.require_version ">= 1.9.0"
VAGRANT_FILE_API_VERSION = "2"

# include yaml for multiple server vagrants
require 'yaml'

# servers: yaml file with vagrant node information
servers = YAML.load_file('nodes.yaml')

# main vagrant configuration
Vagrant.configure(VAGRANT_FILE_API_VERSION) do |config|
    servers.each do |server|
        config.vm.define server["name"] do |nodecfg|
            nodecfg.vm.box = server["box"]
            nodecfg.vm.hostname = server["hostname"]
            nodecfg.vm.network :private_network, ip: server["ip"]

            # provider configuration
            nodecfg.vm.provider :virtualbox do |virt|
                virt.customize [
                    "modifyvm", :id,
                    "--groups", server["group"],
                    "--memory", server["ram"],
                    "--cpus", server["cpus"],
                    "--name", server["name"],
                    "--vrde", server["vrde"],
                    "--vrdeport", server["vrdeport"],
                ]
            end

            # provisioning
            nodecfg.vm.provision "shell", inline: $script

            # ansible provisioning
            # extra_vars is required for ubuntu default user is ubuntu and not
            # vagrant as in other images.
            nodecfg.vm.provision :ansible do |ansible|
                ansible.extra_vars = { ansible_ssh_user: 'ubuntu' }
                ansible.playbook = server["playbook"]
            end
        end
    end
end
